name: boip

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - botorch
  - gpytorch
  - pip
  - python=3.8
  - pytorch::pytorch
  - pytorch::cpuonly
  - pip:
    - numpy
    - pytest
    - tqdm
