name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}

steps:
  - uses: actions/checkout@v1

  - name: Additional info about the build
    shell: bash
    run: |
      uname -a
      df -h
      ulimit -a

  - uses: ./.github/actions/unit-tests.yaml
  # - uses: conda-incubator/setup-miniconda@v2
  #   with:
  #     python-version: ${{ matrix.python-version }}
  #     environment-file: environment.yaml
  #     channels: conda-forge,defaults
  #     activate-environment: test
  #     auto-update-conda: false
  #     auto-activate-base: false
  #     show-channel-urls: true

  # - name: Install package
  #   shell: bash -l {0}
  #   run: |
  #     python -m pip install . --no-deps
      
  # - name: conda list
  #   shell: bash -l {0}
  #   run: conda list

  # - name: Run tests
  #   shell: bash -l {0}
  #   run: |
  #     pip install pytest
  #     pytest -v --cov=pyscreener --cov-report=xml --color=yes

# - name: CodeCov
#   uses: codecov/codecov-action@v1
#   with:
#     file: ./coverage.xml
#     flags: unittests
#     name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
