name: CI

on:
  push:
    branches:
      - "main"
    # paths:
    #   - "boip/**"
    #   - "test/**"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: build info
        run: |
          uname -a
          df -h
          ulimit -a

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: boip
          environment-file: ./.github/test-env.yml
          python-version: ${{ matrix.python-version }}
          auto-update-conda: false
          auto-activate-base: false

      - name: activate conda
        run: conda activate boip

      - name: install package
        shell: bash -l {0}
        run: |
          pip install pytest-cov pytest
          pip install .[test] --no-deps

      - name: conda list
        # shell: bash -l {0}
        run: conda list

      - name: run tests
        # shell: bash -l {0}
        run: pytest -v --color=yes --cov-report=xml

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          verbose: true