name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: build info
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # - uses: ./.github/actions/unit-tests.yaml
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: ./environment.yml
          channels: conda-forge,defaults
          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: install package
        shell: bash -l {0}
        run: |
          pip install . --no-deps
          pip install pytest
          
      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: run tests
        shell: bash -l {0}
        run: |
          pytest -v --cov=pyscreener --cov-report=xml --color=yes

    # - name: CodeCov
    #   uses: codecov/codecov-action@v1
    #   with:
    #     file: ./coverage.xml
    #     flags: unittests
    #     name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
