name: figures

on:
  push:
    branches:
      - "main"
    paths:
      - "data/**"
      - "scripts/figures.py"
      - "scripts/make_all_figs.sh"

jobs:
  figures:
    name: create figures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build info
        run: |
          uname -a
          df -h
          ulimit -a

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          environment-file: ./.github/test-env.yml
          channels: conda-forge,defaults
          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: install package
        run: pip install .[plot] --no-deps
      
      - name: conda list
        run: conda list

      - name: make figures
        run: |
          bash ./scripts/make_all_figs.sh ./figures/github
      
      - name: commit and push
        run: |
          git pull
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"
          git add -f figures/github/*.png
          if [[ `git status --porcelain` ]]; then
            git commit -m "update github figures"
            git push
          fi