name: lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: lint with Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: psf/black@stable
        with:
          src: "./boip"
          options: "-l 100 -t py38 --skip-magic-trailing-comma"
